import json
from pprint import pprint
from backend.agents.supervisor import build_tutoring_graph

def main():
    print("Testing LangGraph Pipeline State Transitions")
    print("=" * 60)
    
    # 1. Prepare initial state simulating a failed grading result
    initial_state = {
        "student_code": "SELECT * FROM employes;",  # Typo in table name
        "grading_raw": {
            "passed": False,
            "score": 0.0,
            "total_tests": 1,
            "passed_tests": 0,
            "test_results": [
                {
                    "test_case_id": 1,
                    "passed": False,
                    "error_message": 'relation "employes" does not exist',
                    "expected_columns": ["id", "name"],
                    "actual_columns": None,
                    "expected_row_count": 5,
                    "actual_row_count": None,
                }
            ],
            "student_error": 'relation "employes" does not exist',
            "student_error_type": "relation_error",
        },
        "grading_results_str": "Test failed: relation 'employes' does not exist",
        "attempt_count": 1,
        "problem_description": "Select all employees from the database.",
        "problem_topic": "SELECT statement",
    }
    
    print("\n[INITIAL STATE] Passed to Graph:")
    pprint(initial_state)
    print("-" * 60)

    # 2. Build and compile the graph
    graph = build_tutoring_graph()
    
    # 3. Stream through the nodes to see state transitions
    print("\n[STARTING GRAPH EXECUTION]")
    for event in graph.stream(initial_state):
        for node_name, node_state_updates in event.items():
            print(f"\n---> [NODE EXECUTED]: {node_name.upper()}")
            print("State updates generated by this node:")
            
            # Remove objects that are hard to print cleanly (like the namedtuple 'classification' if present)
            printable_updates = {}
            for k, v in node_state_updates.items():
                if k == 'classification':
                    printable_updates[k] = "<ClassificationObject>"
                else:
                    printable_updates[k] = v
            
            pprint(printable_updates)
            print("-" * 60)
            
    print("\n[GRAPH EXECUTION COMPLETE]")

if __name__ == "__main__":
    main()
